### ISSUE TITLE
Please add support for bootstrap data-alert

### ISSUE THREAD

**Issue by mwawrusch** [JasonGiedymin/express-messages-bootstrap#1]
Perhaps you can add the data-alert tag to the output to support closing with the built in javascript (http://twitter.github.com/bootstrap/javascript.html#alerts)

Thanks.

Sample from Bootstrap Page:

```
<div class="alert-message warning fade in" data-alert="alert">
          <a class="close" href="#">×</a>
          <p><strong>Holy guacamole!</strong> Best check yo self, you’re not looking too good.</p>
        </div>
```

**Comment by JasonGiedymin** [comment]
Master is synced with the new changes (from my branch 0.0.5b) which include the data-alert tag. Give it a whirl, let me know how it goes.

**Comment by JasonGiedymin** [comment]
Tests passed. Looks good to me. Add issues if you see any.

**Comment by mwawrusch** [comment]
Awesome, thank you and sorry I missed your previous post. I'll let you know if I notice anything.
