### ISSUE TITLE
.fade.in

### ISSUE THREAD

**Issue by rdrey** [JasonGiedymin/express-messages-bootstrap#10]
Hellau

I have already hacked the classes .fade and .in into your component to make my messages' close action animated. (Using bootstrap-transition.js)

I would like to send you a pull request with my changes, but make the extra classes optional and not break your API.

It would be easy to pass in an options dictionary, but now the simple require turned into a function call:

``` javascript
app.dynamicHelpers({ messages: require('express-messages-bootstrap')({fade: true}) });
```

Can you think of a different, non-hacky way of passing options to your component?

**Comment by JasonGiedymin** [comment]
Looks like it's being handled by: https://github.com/JasonGiedymin/express-messages-bootstrap/pull/11

Expect a response soon

**Comment by JasonGiedymin** [comment]
NPM Updated with 0.1.0

See
https://github.com/JasonGiedymin/express-messages-bootstrap/commit/1b97ad1185a3118d4d6c570e79f4dd74f2d32950

See tests for demos on adding additional classes such as 'fade in'
