### ISSUE TITLE
Add an example

### ISSUE THREAD

**Issue by clemsos** [JasonGiedymin/express-messages-bootstrap#17]
Could you add an example to the rep please?
I am using it but not sure how to make it works exactly ...
thanks for the good job !

**Comment by sonson** [comment]
+1, please

**Comment by sonson** [comment]
Finally I found the example in the `test` directory, but more informations in the README would be very helpful.

I also don't found the new version 1.0.0 in NPM repository, just the old version 0.1?! Is there a public version of express-messages-bootstrap that work with express V. 3 in the NPM repository somewhere?

Thanks for your work.

**Comment by JasonGiedymin** [comment]
Published.

**Comment by clemsos** [comment]
thanks !
