### ISSUE TITLE
plans to support bootstrap 2?

### ISSUE THREAD

**Issue by RandomEtc** [JasonGiedymin/express-messages-bootstrap#4]
The default alert class changed from `alert` to `alert-message` - we can fork and make the change ourselves of course, but I thought it was worth asking first in case you're planning another release.

**Comment by JasonGiedymin** [comment]
Sure I'll change it! :-)

-Jason

**Comment by apb2006** [comment]
I would also like to see a bootstrap 2 version

**Comment by 525c1e21-bd67-4735-ac99-b4b0e5262290** [comment]
bump

**Comment by JasonGiedymin** [comment]
Will try to get to this asap.

-Jason

**Comment by akagomez** [comment]
In the meantime: https://gist.github.com/1937108

**Comment by JasonGiedymin** [comment]
Trunk, Tests, updated. NPM published as v0.0.7. :-)

http://search.npmjs.org/#/express-messages-bootstrap
