### ISSUE TITLE
Error messages are not vertically centered

### ISSUE THREAD

**Issue by tbergeron** [JasonGiedymin/express-messages-bootstrap#7]
Hi,

Due to the usage of `<p></p>` in the messages, they're not vertically aligned.

I'm using Chrome by the way.

See with `<p></p>` (package took from npm)
http://i.imgur.com/ciR6u.png

And then I removed the `<p></p>` in your code and it gives me a well aligned version:
http://i.imgur.com/8JWJJ.png

Could you check this out please?

Thanks!

**Comment by JasonGiedymin** [comment]
I agree with you, any formatting should be supplied by the user. I'll roll this into the merge.

**Comment by JasonGiedymin** [comment]
Pre-formatted messages removed in trunk and was pushed to NPM in v0.0.8 http://search.npmjs.org/#/express-messages-bootstrap.

Thanks for your input!!!

**Comment by tbergeron** [comment]
No problem, always glad to help! Keep up the good job :-)

**Comment by drewish** [comment]
Oh, cool I was just about to complain about this ;)
